services:

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    stop_signal: SIGINT
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users -d usersdb"]
      interval: 2s
      timeout: 3s
      retries: 20

  backend:
    build: { context: ., dockerfile: backend/Dockerfile }
    env_file: backend/.env
    depends_on: 
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    volumes: ["./backend:/app"]
    stop_signal: SIGINT
    stop_grace_period: 5s

  frontend:
    build: { context: ., dockerfile: frontend/Dockerfile }
  environment:
    VITE_API_URL: http://localhost:8000/api
    CHOKIDAR_USEPOLLING: "1"
  ports: ["5173:5173"]
  volumes:
    - ./frontend:/app
    - /app/node_modules
  working_dir: /app
  command:
    - /bin/sh
    - -lc
    - |
      if [ -f package-lock.json ]; then npm ci --no-audit --no-fund; else npm i --no-audit --no-fund; fi
      if npm run | grep -qE '^  dev'; then
        npm run dev -- --host 0.0.0.0 --port 5173
      elif npm run | grep -qE '^  start'; then
        npm run start -- --host 0.0.0.0 --port 5173
      else
        echo "No dev/start script found in package.json"; cat package.json; exit 1
      fi
  stop_signal: SIGINT
  stop_grace_period: 5s

volumes:
  pgdata:
