"""
This is a Django middleware that records the user’s last activity timestamp on every request.
"""

from django.utils import timezone

from .models.profile import Profile


class LastActivityMiddleware:
    """
    This is a Django middleware that records the user’s last activity timestamp on every request.
    """
    def __init__(self, get_response):
        """
        Stores the next callable in the middleware chain.
        """
        self.get_response = get_response

    def __call__(self, request):
        """
        Process the request and record the user's last activity timestamp.

        Args:
            request (django.http.HttpRequest): Incoming HTTP request.

        Returns:
            django.http.HttpResponse, the response generated by the downstream handler.
        """
        response = self.get_response(request)
        user = getattr(request, "user", None)
        if user and user.is_authenticated:
            Profile.objects.filter(user=user).update(last_activity=timezone.now())
        return response
